name: Deploy to GitHub ðŸš€

on:
  release:
    types: [created]

jobs:
  deploy-github:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: "https://npm.pkg.github.com"
          token: ${{ secrets.GITHUB_TOKEN }}
          always-auth: true
      - run: yarn install
      - run: yarn build --print-label
      - run: yarn test
      - run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
